kind: pipeline
name: default

steps:
- name: ssh commands
  image: appleboy/drone-ssh
  environment:
    SSH_KEY:
      from_secret: ssh_key
  settings:
    host: 107.167.190.8
    username: centos
    port: 22
  scripts:
  - echo "$ssh_key"
  - mkdir aaaa
    
