kind: pipeline
name: default

steps:
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 107.167.190.8
    username: centos
    secrets: [ ssh-key ]
#    passowrd:
#      from_secret: go-api
    port: 22
    script:
      - mkdir test1
    
