kind: pipeline
name: default

steps:
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 107.167.190.8
    username: centos
    port: 22
    ssh_key:
      from_secret: ssh_key
    script:
      - mkdir test1
    
